# base-image for python on any machine using a template variable,
# see more about dockerfile templates here:http://docs.resin.io/pages/deployment/docker-templates
FROM balenalib/%%BALENA_ARCH%%-alpine-python:3.8-3.12-build

ENV POETRY_VERSION=1.0.10

# Set our working directory
WORKDIR /usr/src/app

RUN pip install "poetry==$POETRY_VERSION"

# This will copy all files in our root to the working  directory in the container
COPY . ./

RUN poetry install --no-dev

CMD ["poetry", "run", "main"]
